### ISSUE TITLE
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -4

### ISSUE THREAD

**Issue by lsmith77** [ericdaugherty/itunesexport-scala#2]
```
java -jar -Xms1024m -Xmx2048m itunesexport.jar -library="/volume1/itunes/iTunes Music Library.xml" -outputDir="/volume1/itunes/playlists"
iTunesExport 2.2.2 http://www.ericdaugherty.com/dev/itunesexport/
Use -h or -? to display available parameters
Parsing Music Library: /volume1/itunes/iTunes Music Library.xml
Writing output to: /volume1/itunes/playlists
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -4
	at java.lang.String.substring(String.java:1927)
	at com.ericdaugherty.itunesexport.formatter.Formatter.includeTrack(Formatter.scala:98)
	at com.ericdaugherty.itunesexport.formatter.Formatter$$anonfun$filterTracks$1.apply(Formatter.scala:88)
	at com.ericdaugherty.itunesexport.formatter.Formatter$$anonfun$filterTracks$1.apply(Formatter.scala:88)
	at scala.Iterable$class.filter(Iterable.scala:185)
	at scala.RandomAccessSeq$Mutable$$anon$11.scala$Seq$$super$filter(RandomAccessSeq.scala:109)
	at scala.Seq$class.filter(Seq.scala:304)
	at scala.RandomAccessSeq$Mutable$$anon$11.filter(RandomAccessSeq.scala:109)
	at com.ericdaugherty.itunesexport.formatter.Formatter.filterTracks(Formatter.scala:88)
	at com.ericdaugherty.itunesexport.formatter.M3UFormatter$$anonfun$writePlaylist$1.apply(M3UFormatter.scala:19)
	at com.ericdaugherty.itunesexport.formatter.M3UFormatter$$anonfun$writePlaylist$1.apply(M3UFormatter.scala:17)
	at com.ericdaugherty.itunesexport.formatter.Formatter.withPrintWriter(Formatter.scala:70)
	at com.ericdaugherty.itunesexport.formatter.Formatter.withPrintWriter(Formatter.scala:58)
	at com.ericdaugherty.itunesexport.formatter.M3UFormatter.writePlaylist(M3UFormatter.scala:17)
	at com.ericdaugherty.itunesexport.formatter.Formatter.exportPlaylist(Formatter.scala:82)
	at com.ericdaugherty.itunesexport.console.ConsoleExport$$anonfun$main$1.apply(ConsoleExport.scala:104)
	at com.ericdaugherty.itunesexport.console.ConsoleExport$$anonfun$main$1.apply(ConsoleExport.scala:104)
	at scala.Iterator$class.foreach(Iterator.scala:414)
	at scala.collection.mutable.ResizableArray$$anon$1.foreach(ResizableArray.scala:66)
	at scala.Iterable$class.foreach(Iterable.scala:256)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:26)
	at com.ericdaugherty.itunesexport.console.ConsoleExport$.main(ConsoleExport.scala:104)
	at com.ericdaugherty.itunesexport.console.ConsoleExport.main(ConsoleExport.scala)
```

I guess the issue is that my iTunes library is rather large.

**Comment by lsmith77** [comment]
BTW I do have most (all?) playlists exported but lots of files missing in the playlists.

**Comment by ericdaugherty** [comment]
This specific error occurs when you have a track in your library that is an 'MP3' track, but there is no location set in the library for that track. This can be because the file is not on the local computer but in the library (IE, in iTunes Cloud, iTunes Music, etc).  But it can be other reasons as well.

Ideally the app would handle this much more gracefully, but it really isn't maintained/supported. The best way to figure out what is up is to search through your library file (xml file) and find all the tracks that are MP3s but don't have locations. And then try to fix it. I understand with a large library this may be challenging.

**Comment by lsmith77** [comment]
thx for the hint!

**Comment by lsmith77** [comment]
alright .. my xpath skills are currently non-existant .. but maybe you can give me an example of this?

I am trying to figure out if in the described case there is no `<key>Location</key` or if there is no `<string>` tag following .. or the `<string>` tag is empty. with an example it would help me pin-point what kind of xpath query I need to learn to write :)
