### ISSUE TITLE
Exception in thread "main" java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by patatero** [ericdaugherty/itunesexport-scala#4]
I've got this error when I tried exporting my playlists:

```
java -jar itunesexport.jar -library="Library.xml"  
iTunesExport 2.2.3 http://www.ericdaugherty.com/dev/itunesexport/
Use -h or -? to display available parameters
Parsing Music Library: Library.xml
Exception in thread "main" java.lang.IllegalAccessError: superclass access check failed: class com.ericdaugherty.itunesexport.NonDTDSaxParserFactory (in unnamed module @0x12fcd461) cannot access class com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.jaxp to unnamed module @0x12fcd461
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:488)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.xml/javax.xml.parsers.FactoryFinder.getProviderClass(FactoryFinder.java:108)
	at java.xml/javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:184)
	at java.xml/javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:147)
	at java.xml/javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:227)
	at java.xml/javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:181)
	at scala.xml.factory.XMLLoader$class.parser(XMLLoader.scala:28)
	at scala.xml.XML$.parser(XML.scala:57)
	at scala.xml.factory.XMLLoader$class.loadFile(XMLLoader.scala:49)
	at scala.xml.XML$.loadFile(XML.scala:57)
	at com.ericdaugherty.itunesexport.parser.Library.<init>(Library.scala:32)
	at com.ericdaugherty.itunesexport.console.ConsoleExport$.main(ConsoleExport.scala:56)
	at com.ericdaugherty.itunesexport.console.ConsoleExport.main(ConsoleExport.scala)
```

I'm using macOS Catalina.

```
$ java -version                                                                                        
openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment Homebrew (build 18.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.1+0, mixed mode, sharing)

$ which java
/usr/local/opt/openjdk/bin/java
```

Do I need to use older version of Java?

**Comment by ericdaugherty** [comment]
Yes, you'll need to use an older version of Java. The library used originally has been removed from the latest version. I'm not sure where the cutoff is, but I've only recently heard feedback on this so I assume anything older than 18 should work.

**Comment by ericdaugherty** [comment]
I updated the 'main' console version to be a go version instead of this (outdated) scala version. 

You can find download links here: https://www.ericdaugherty.com/dev/itunesexport/

It doesn't quite have all the same options, but will hopefully be 'good enough' for most folks and not have any Java dependency issues.

**Comment by patatero** [comment]
I tried the script with the previous versions of Java... doesn't work with v16 but it works with v15. Here's that works for me:

```
$ java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
```

Maybe you'd want to update the readme...
